[WIP] Joakim's and Pilars library challenge
CraftAcademy/library-challenge pull request #82
Opened 2019-01-26 13:01 UTC by nevroje

PR

2019-01-26 14:17 UTC, nevroje commented
Trying to set up tests for a return date so we know if a book is available.

2019-01-30 13:19 UTC, faraznaeem requested changes
You have done a good attempt, but the code isn't working for small reasons as syntax errors. Make sure to put more attention on the small details in the future.

2019-01-30 13:19 UTC, faraznaeem commented on lib/data.yml
> +---
Why do you have two different yml files with books?

2019-01-30 13:19 UTC, faraznaeem commented on lib/library.rb
> +    @title = title #not sure how to link to yaml file
Delete comments in the future before submitting the code

2019-01-30 13:19 UTC, faraznaeem commented on spec/borrower_spec.rb
> +    He or she 'is expected to have a :name on initialize' do
this is probably not working, that is beacuse of the syntax error. Remember to have proper `it` blocks

2019-01-30 13:19 UTC, faraznaeem commented on spec/library_account_spec.rb
> +    #not sure but I think we need to set up user accounts for borrowers? plus are there extra brackets above?
Comments in code is a no-go

2019-04-08 04:58 UTC, closed without merging